"""Corrected readFlag column name.

Revision ID: 7566d8e773a7
Revises: e8d0b05a140f
Create Date: 2025-05-08 10:45:28.249528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7566d8e773a7'
down_revision = 'e8d0b05a140f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareReports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readFlag', sa.Integer(), nullable=False))
        batch_op.drop_column('redaFlag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareReports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redaFlag', sa.INTEGER(), nullable=False))
        batch_op.drop_column('readFlag')

    # ### end Alembic commands ###
