"""Added sharedDate in shareReports table

Revision ID: d21be403f096
Revises: 
Create Date: 2025-05-03 23:05:39.481107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21be403f096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareReports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharedDate', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareReports', schema=None) as batch_op:
        batch_op.drop_column('sharedDate')

    # ### end Alembic commands ###
