"""Added report readFlag column to the shareReport table.

Revision ID: e8d0b05a140f
Revises: 0f6f5a953ace
Create Date: 2025-05-08 10:44:49.664729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d0b05a140f'
down_revision = '0f6f5a953ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareReports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redaFlag', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareReports', schema=None) as batch_op:
        batch_op.drop_column('redaFlag')

    # ### end Alembic commands ###
